GestionP/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django import setup
setup()
admin.autodiscover()

urlpatterns =  [
    url(r'^$', include('RegistroApp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^usuarios/', include('usuarios.urls')),
    #url(r'^cliente/', include('cliente.urls')),
    url(r'^roles/',include('roles.urls')),
    url(r'^proyectos/',include('proyectos.urls')),
    url(r'^equipos/', include('equipos.urls')),
    url(r'^flujos/', include('flujos.urls')),
    url(r'^actividades/', include('actividades.urls')),
    url(r'^userStories/', include('userStories.urls')),
    url(r'^sprints/', include('sprints.urls')),
    url(r'^trabajos/', include('trabajos.urls')),
]

proyectos/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
admin.autodiscover()
from .views import lista_proyectos, registra_proyecto, RegisterSuccessView, editar_proyecto, buscar_proyecto, detalle_proyecto, \
        proyecto_iniciar, proyecto_finalizar, proyecto_aprobar, proyecto_eliminar, proyecto_rechazar, detalle_proyecto_cancelar, proyecto_cancelar

urlpatterns = [
        url(r'^registrar/$',registra_proyecto, name='registrar_proyectos'),
        url(r'^$',lista_proyectos, name='listar_proyectos'),
        url(r'^register/success/$',RegisterSuccessView ,name='RegisterSuccessView'),
        url(r'^modificar/(?P<id_proyecto>\d+)$', editar_proyecto, name='edit_proyecto'),
        url(r'^cancelar/(?P<id_proyecto>\d+)$', proyecto_cancelar, name='proyecto_cancelar'),
        url(r'^search/$',buscar_proyecto, name='buscar_proyectos'),
        url(r'^(?P<id_proyecto>\d+)$', detalle_proyecto, name='detalle_proyecto'),
        url(r'^detallecancelar/(?P<id_proyecto>\d+)$', detalle_proyecto_cancelar, name='detalle_proyecto_cancelar'),
#MANIPULACION DE LOS ESTADOS DE LOS PROYECTOS
        url(r'^iniciar/(?P<id_proyecto>\d+)$', proyecto_iniciar, name='proyecto_iniciar'),
        url(r'^finalizar/(?P<id_proyecto>\d+)$', proyecto_finalizar, name='proyecto_iniciar'),
        url(r'^aprobar/(?P<id_proyecto>\d+)$', proyecto_aprobar, name='proyecto_iniciar'),
        url(r'^eliminar/(?P<id_proyecto>\d+)$', proyecto_eliminar, name='proyecto_iniciar'),
        url(r'^rechazar/(?P<id_proyecto>\d+)$', proyecto_rechazar, name='proyecto_iniciar'),
]
print(urlpatterns)

roles/urls.py
from django.conf.urls import url
from django.contrib import admin
admin.autodiscover()

from .views import crear_rol, detalle_rol, lista_roles, editar_rol, RegisterSuccessView, eliminar_rol

urlpatterns =  [
    url(r'^crear/$', crear_rol, name='crear_rol'),
    url(r'^$',lista_roles,name='lista_roles'),
    url(r'^(?P<id_rol>\d+)$', detalle_rol, name='detalle_rol'),
    url(r'^eliminar/(?P<id_rol>\d+)$', eliminar_rol, name='eliminar_rol'),
    url(r'^modificar/(?P<id_rol>\d+)$', editar_rol, name='editar_rol'),
    url(r'^register/success/$',RegisterSuccessView.as_view()),
]
print(urlpatterns)

proyectos/models.py
from django.db import models
from django.contrib.auth.models import User, Group

# Create your models here.
ESTADOS = (

    ('NUE', 'Nuevo'), # cuando se crea
    ('PRO', 'Produccion'), # cuando se inicia
    ('FIN','Finalizado'), # cuando se termina
    ('APR', 'Aprobado'), # cuando se aprueba uno finalizado
    ('ELI','Eliminado'), # cuando se elimina o cancela
)

class Proyecto(models.Model):
    """
    Clase del Modelo que representa al proyecto con sus atributos.
    nombre: Cadena de caracteres
    siglas: siglas del nombre del proyecto
    descripcion: Un campo de texto
    fecha_ini: Fecha que indica el inicio de un proyecto
    fecha_fin: Fecha que indica el fin estimado de un proyecto
    estado: Enum de los tipos de estados por los que puede pasar un proyecto: Pendiente, Anulado, Activo y Finalizado
    cliente: Clave foranea a la tabla usuario
    """
    nombre = models.CharField(max_length=50, verbose_name='Nombre', unique=True)
    nombreCorto = models.CharField(max_length=20, verbose_name='Nombre corto', unique=True)
    descripcion = models.TextField(verbose_name='Descripcion')
    fecha_ini = models.DateField(verbose_name='Fecha de inicio', null=True)
    fecha_fin = models.DateField(verbose_name='Fecha de Finalizacion', null=True)
    fecha_apr = models.DateField(verbose_name='Fecha de Aprobacion', null=True)
    fecha_eli = models.DateField(verbose_name='Fecha de Eliminacion', null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    estado = models.CharField(max_length=3, choices=ESTADOS, default='NUE')
    #cliente = models.ForeignKey(Cliente, related_name='cliente')
    observacion = models.TextField(verbose_name='Observacion')

    def __unicode__(self):
        return self.id

    #class Meta:
    #    verbose_name = 'proyecto'
    #    verbose_name_plural = 'proyectos'

proyectos/forms.py
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms
from proyectos.models import Proyecto
from django.contrib.admin.widgets import FilteredSelectMultiple


ESTADOS = (

    ('PRO', 'Produccion'),
    ('APR', 'Aprobado'),
    ('FIN','Finalizado'),
    ('ELI','Eliminado'),
)


class ProyectoForm(ModelForm):
    #lider = forms.ModelChoiceField(queryset=User.objects.filter(is_active=True))
    #comite = forms.ModelMultipleChoiceField(queryset=User.objects.filter(is_active=True),
                                            #widget=FilteredSelectMultiple("Comite", is_stacked=False))

    class Meta:
        model = Proyecto
        exclude = ['fecha_ini', 'fecha_fin', 'fecha_fin', 'fecha_apr', 'fecha_eli', 'fecha_creacion', 'estado']

class CancelarProyectoForm(ModelForm):
    class Meta:
        model = Proyecto
        fields = ('descripcion',)

proyectos/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.template import RequestContext
from django.shortcuts import render_to_response, get_object_or_404,redirect
from django.contrib.auth.models import User, Group
from proyectos.models import Proyecto
from proyectos.forms import ProyectoForm
from datetime import datetime
from django.http import HttpResponse, HttpResponseRedirect
from equipos.models import MiembroEquipo
from django.db.models import Q
from django.shortcuts import render
from equipos.forms import crearEquipoForm
from proyectos.forms import CancelarProyectoForm


@login_required
def lista_proyectos(request):

    userLogueadoID = request.user.id  #User Logueado ID
    #print "usuario ID %s" % userLogueado
    rolSM = Group.objects.filter(name = "Scrum Master")
    permission_required('proyectos')
    #permission_required(perm=rolSM)


    if request.user.is_staff:
        proyectos = Proyecto.objects.all()
    else:
        proyUsuario = MiembroEquipo.objects.filter(usuario_id=userLogueadoID)
        for y in proyUsuario:
            print ("Proyecto pertenece a usuario: %s" % y.proyecto_id)

        #proyectos = Proyecto.objects.all().exclude(id__in = [x.id for x in request.user.usergallery_set()])
        proyectos = Proyecto.objects.filter(id__in = [x.proyecto_id for x in proyUsuario])
        #proyecto = Proyecto.objects.get(id=id_proyecto)

        equipos = MiembroEquipo.objects.filter(rol = rolSM)
        #equipos = MiembroEquipo.objects.filter()

        #haySM = MiembroEquipo.objects.filter(rol = rolSM, proyecto_id = miembro.proyecto_id)

    return render_to_response('proyectos/listar_proyectos.html', {'proyectos': proyectos, 'rolSM': rolSM},
                              context_instance=RequestContext(request))


@login_required
def registra_proyecto(request):
    """
    Vista para registrar un nuevo proyecto
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    HttpResponseRedirect('/proyectos/register/success') si el rol lider fue correctamente asignado o
    render_to_response('proyectos/registrar_proyecto.html',{'formulario':formulario}, context_instance=RequestContext(request)) al formulario
    """

    if request.method == 'POST':
        formulario = ProyectoForm(request.POST)
        if formulario.is_valid():
            nombre = formulario.cleaned_data['nombre']
            nombrecorto = formulario.cleaned_data['nombreCorto']
            descripcion = formulario.cleaned_data['descripcion']
            #cliente = formulario.cleaned_data['cliente']

            proyectoNvo = Proyecto(nombre=nombre, nombreCorto=nombrecorto, descripcion=descripcion)
            proyectoNvo.save()
            return redirect('/proyectos/')
    else:
        formulario = ProyectoForm()
    return render_to_response('proyectos/registrar_proyectos.html', {'formulario': formulario, 'mensaje': 1000}, context_instance=RequestContext(request))

@login_required
def RegisterSuccessView(request):
    """
    Vista llamada en caso de creacion correcta de un proyecto, redirige a un template de exito
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    render_to_response('proyectos/creacion_correcta.html', context_instance=RequestContext(request))
    """
    return render_to_response('proyectos/creacion_correcta.html', context_instance=RequestContext(request))

@login_required
def editar_proyecto(request, id_proyecto):
    """
    Vista para editar un proyecto
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    id_proyecto: referencia al proyecto de la base de datos
    return: HttpResponseRedirect('/proyectos/register/success/') cuando el formulario es validado correctamente o render_to_response('proyectos/editar_proyecto.html', { 'proyectos': proyecto_form, 'nombre':nombre}, context_instance=RequestContext(request))
    """
    proyecto = Proyecto.objects.get(id=id_proyecto)
    nombre = proyecto.nombre
    if request.method == 'POST':
        # formulario enviado
        proyecto_form = ProyectoForm(request.POST, instance=proyecto)
        if proyecto_form.is_valid():
            # formulario validado correctamente
            proyecto_form.save()
            return redirect('/proyectos/')
            #return HttpResponseRedirect('/proyectos/register/success/')
    else:
        # formulario inicial
        proyecto_form = ProyectoForm(instance=proyecto)
    return render_to_response('proyectos/editar_proyecto.html', {'proyectos': proyecto_form, 'nombre': nombre},
                              context_instance=RequestContext(request))

@login_required
def buscar_proyecto(request):
    """
    vista para buscar los proyectos del sistema
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    return: render_to_response('proyectos/listar_proyectos.html', {'datos': results}, context_instance=RequestContext(request))
    """
    query = request.GET.get('q', '')
    if query:
        qset = (
            Q(nombre__contains=query)
        )
        results = Proyecto.objects.filter(qset).distinct()
    else:
        results = []

    return render_to_response('proyectos/listar_proyectos.html', {'proyectos': results},
                              context_instance=RequestContext(request))


@login_required
def detalle_proyecto(request, id_proyecto):
    """
    Vista para ver los detalles del proyecto del sistema
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    id_proyecto: referencia al proyecto de la base de datos
    return: render_to_response('proyectos/detalle_proyecto.html', {'proyecto': dato}, context_instance=RequestContext(request))
    """
    rolSM = Group.objects.filter(name="Scrum Master")
    #permission_required(perm=rolSM)
    permission_required('proyectos')
    dato = get_object_or_404(Proyecto, pk=id_proyecto)
    return render_to_response('proyectos/detalle_proyecto.html', {'proyecto': dato},
                              context_instance=RequestContext(request))

@login_required
def detalle_proyecto_cancelar(request, id_proyecto):
    """
    Vista para ver los detalles del proyecto del sistema
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    id_proyecto: referencia al proyecto de la base de datos
    return: render_to_response('proyectos/detalle_proyecto.html', {'proyecto': dato}, context_instance=RequestContext(request))
    """
    rolSM = Group.objects.filter(name="Scrum Master")
    #permission_required(perm=rolSM)
    permission_required('proyectos')
    dato = get_object_or_404(Proyecto, pk=id_proyecto)
    return render_to_response('proyectos/detalle_proyecto_cancelar.html', {'proyecto': dato},
                              context_instance=RequestContext(request))

# cambio de estado de proyecto
@login_required
def proyecto_iniciar(request, id_proyecto):
    """
    Vista para iniciar un proyecto del sistema
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    id_proyecto: referencia al proyecto de la base de datos
    render_to_response('proyectos/detalle_proyecto.html', {'proyecto': dato}, context_instance=RequestContext(request))
    """
    rolSM = Group.objects.filter(name = "Scrum Master")
    equipo = MiembroEquipo.objects.filter(rol = rolSM, proyecto_id = id_proyecto)
    if equipo.count() == 0:
        mensaje = 102 # no puede iniciar el proyecto sin asignar Scrum Master al equipo
        proyectos = Proyecto.objects.all()
        #proyecto = Proyecto.objects.get(id=id_proyecto)
        rolSM = Group.objects.filter(name = "Scrum Master")
        equipos = MiembroEquipo.objects.filter(rol = rolSM)
        return render_to_response('proyectos/listar_proyectos.html', {'proyectos': proyectos, 'mensaje': mensaje}, context_instance=RequestContext(request))
    else:
        proyectos = Proyecto.objects.get(id=id_proyecto)
        proyectos.estado = "PRO"
        proyectos.fecha_ini = datetime.now()
        proyectos.save()

        # listar proyectos
        proyectos = Proyecto.objects.all()
        return render_to_response('proyectos/listar_proyectos.html', {'proyectos': proyectos},
                              context_instance=RequestContext(request))

@login_required
def proyecto_finalizar(request, id_proyecto):
    """
    Vista para finalizar un proyecto del sistema
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    id_proyecto: referencia al proyecto de la base de datos
    return: render_to_response('proyectos/detalle_proyecto.html', {'proyecto': dato}, context_instance=RequestContext(request))
    """
    proyectos = Proyecto.objects.get(id=id_proyecto)
    proyectos.estado = "FIN"
    proyectos.fecha_fin = datetime.now()
    proyectos.save()

    # listar proyectos
    proyectos = Proyecto.objects.all()
    return render_to_response('proyectos/listar_proyectos.html', {'proyectos': proyectos},
                          context_instance=RequestContext(request))

@login_required
def proyecto_aprobar(request, id_proyecto):
    """
    Vista para aprobar un proyecto del sistema
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    id_proyecto: referencia al proyecto de la base de datos
    return: render_to_response('proyectos/detalle_proyecto.html', {'proyecto': dato}, context_instance=RequestContext(request))
    """
    proyectos = Proyecto.objects.get(id=id_proyecto)
    proyectos.estado = "APR"
    proyectos.fecha_apr = datetime.now()
    proyectos.save()

    # listar proyectos
    proyectos = Proyecto.objects.all()
    return render_to_response('proyectos/listar_proyectos.html', {'proyectos': proyectos},
                          context_instance=RequestContext(request))

@login_required
def proyecto_eliminar(request, id_proyecto):
    """
    Vista para eliminar un proyecto del sistema

proyectos/templates/proyectos/cambiar_estado_proyecto.html
{% extends 'base2.html' %}
{% block title %}
	GestionP - Modificar Estado
{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="es-PY" >
<head>
<link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />

<script type="text/javascript">window.__admin_media_prefix__ = "/static/usuario/";</script>

<meta name="robots" content="NONE,NOARCHIVE" />
</head>

<body class="">

<!-- Container -->
<div id="container">


<div class="breadcrumbs">
<a href="/proyectos/">Proyectos</a>
&rsaquo; Estados Proyecto
</div>

    <!-- Content -->
    <div id="content" class="colM">
    <h1>Cambiar Estado del Proyecto {{ nombre|title }} </h1>
<form action="" method="post">{% csrf_token %}
    <ul class="errorlist">
            {% if  mensaje == 0 %}
            <li>Error: El proyecto no posee la cantidad suficiente, o posee un numero par de miembros del comite. Modifiquelos, por favor.
                <a href="/proyectos/modificar/{{ dato }}" class="btn btn-danger">Modificar</a></li>
                {% elif mensaje == 1 %}
                <li>Error: El proyecto posee miembros del comite que no pertenecen a ninguna fase.. Favor asignarlos a una..
                <a href="/fases/proyecto/{{ dato }}" class="btn btn-danger">Asignar Rol</a></li>
                {% elif mensaje == 2 %}
                <li>Error: El proyecto no posee ninguna fase. Agregue una o mas fases al proyecto, por favor.
                <a href="/fases/proyecto/{{ dato }}" class="btn btn-danger">Agregar Fases</a></li>
                {% elif mensaje == 3 %}
                <li>Error: La fase {{ fase.nombre }} aun no posee Tipos de Item.
                <a href="/tiposDeItem/registrar/{{ fase }}" class="btn btn-danger">Agregar Tipo de Item</a></li>
            {% endif %}
        </ul>

    {{ proyectos }}

    <input class="btn btn-primary" type="submit" value="Guardar cambios">
</form>


        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>
{% endblock %}

proyectos/templates/proyectos/creacion_correcta.html
{% extends 'base2.html' %}
{% block title %}
GestionP - Creación Correcta
{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="es-PY" >
<head>
    <meta http-equiv="Refresh" content="2; /proyectos/">
    <link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />

    <script type="text/javascript">window.__admin_media_prefix__ = "/static/usuario/";</script>

    <meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class="">

<!-- Container -->

    <!-- Content -->
    <div id="content" class="change-list" style="width: 1100px">


        <h1>Registro de Proyecto exitoso</h1>


        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>

<!-- END Container -->

</body>
</html>
{% endblock %}

proyectos/templates/proyectos/detalle_proyecto.html
{% extends 'base2.html' %}
{% block title %}
	GestionP - Detalles del Proyecto
{% endblock %}
{% block content %}
<head>
<link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/usuario/css/forms.css" />
</head>


<div id="content" class="change-list" style="width: 1100px">
    <h1>Detalles del {{proyecto.nombre|title}}</h1>
       <fieldset class="module aligned wide">
    <form method="post">{% csrf_token %}
    <div class="form-row">
            <h3><p><div><strong>Nombre: </strong>{{ proyecto.nombre }}</div></h3></p>
            <h3><p><div><strong>Codigo: </strong>{{ proyecto.id }}</div></h3></p>
            <h3><p><div><strong>Descripción: </strong>{{ proyecto.descripcion }}</div></h3></p>
            <h3><p><div><strong>Estado: </strong>{{ proyecto.get_estado_display }}</div></h3></p>
            <h3><p><div><strong>Fecha de Inicio: </strong>{{ proyecto.fecha_ini }}</div></h3></p>
            {% if proyecto.fecha_fin != none %}
                <h3><p><div><strong>Fecha de Finalizacion: </strong>{{ proyecto.fecha_fin}}</div></h3></p>
            {% endif %}
            <!--<div><strong>Observaciones: </strong>{{ proyecto.observaciones }}</div>-->
            {% for integrante in comite %}
                <h3><p>{{ integrante.first_name}} {{ integrante.last_name}}</h3></p>
            {% endfor %}
    </div>
        <div class="submit-row">
                <input type='submit' value='Retornar' onClick='history.go(-1);'>
        </div>
    </form>
       </fieldset>
</div>

{% endblock %}

proyectos/templates/proyectos/detalle_proyecto_cancelar.html
{% extends 'base2.html' %}
{% block title %}
	GestionP - Detalles del Proyecto Cancelar
{% endblock %}
{% block content %}
<head>
<link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/usuario/css/forms.css" />
</head>


<div id="content" class="change-list" style="width: 1100px">
    <h1>Detalles del {{proyecto.nombre|title}}</h1>
       <fieldset class="module aligned wide">
    <form method="post">{% csrf_token %}
    <div class="form-row">
            <h3><p><div><strong>Nombre: </strong>{{ proyecto.nombre }}</div></h3></p>
            <h3><p><div><strong>Codigo: </strong>{{ proyecto.id }}</div></h3></p>
            <h3><p><div><strong>Descripción: </strong>{{ proyecto.descripcion }}</div></h3></p>
            <h3><p><div><strong>Descripción de Cancelación: </strong>{{ proyecto.descripcion }}</div></h3></p>
            <h3><p><div><strong>Estado: </strong>{{ proyecto.get_estado_display }}</div></h3></p>
            <h3><p><div><strong>Fecha de Inicio: </strong>{{ proyecto.fecha_ini }}</div></h3></p>
            {% if proyecto.fecha_fin != none %}
                <h3><p><div><strong>Fecha de Finalizacion: </strong>{{ proyecto.fecha_fin}}</div></h3></p>
            {% endif %}
            <!--<div><strong>Observaciones: </strong>{{ proyecto.observaciones }}</div>-->
            {% for integrante in comite %}
                <h3><p>{{ integrante.first_name}} {{ integrante.last_name}}</h3></p>
            {% endfor %}
    </div>
        <div class="submit-row">
                <input type='submit' value='Retornar' onClick='history.go(-1);'>
        </div>
    </form>
       </fieldset>
</div>

{% endblock %}

proyectos/templates/proyectos/editar_proyecto.html
{% extends 'base2.html' %}
{% block title %}
	GestionP - Modificar Proyecto
{% endblock %}
{% block content %}
<head>
<link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/usuario/css/forms.css" />
</head>
    <div id="content" class="change-list" style="width: 1100px">
    <h1>Modificar Proyecto {{ nombre|title }}</h1>
        <fieldset class="module aligned wide">
<form method="post">{% csrf_token %}
    <div class="form-row">
    {{ proyectos.as_p }}
        </div>
    <div class="submit-row">
        <input type='submit' value='Cancelar' onClick='history.go(-1);'>
        <input type="submit" value="Guardar Cambios" />
    </div>
</form>
            </fieldset>
    </div>
{% endblock %}

proyectos/templates/proyectos/proyecto_cancelar.html
{% extends 'base2.html' %}
{% block title %}
	GestionP - ProyectoCancelar
{% endblock %}
{% block content %}
<head>
<link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/usuario/css/forms.css" />
</head>
    <div id="content" class="change-list" style="width: 1100px">
    <h1>Agregar Descripcion de Cancelación {{ nombre|title }}</h1>
        <fieldset class="module aligned wide">
<form method="post">{% csrf_token %}
    <div class="form-row">
    {{ proyectos.as_p }}
        </div>
    <div class="submit-row">
        <input type='submit' value='Retornar' onClick='history.go(-1);'>
        <input type="submit" value="Guardar Cambios" />
    </div>
</form>
            </fieldset>
    </div>
{% endblock %}

proyectos/templates/proyectos/registrar_proyectos.html
{% extends 'base2.html' %}
{% block title %}
	GestionP - Nuevo Proyecto
{% endblock %}
{% block content %}
    <head>
<link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/usuario/css/forms.css" />

</head>

                <div id="content" class="change-list" style="width: 1100px">
                <h1>Crear Proyecto</h1>
       <fieldset class="module aligned wide">
<form method="post">{% csrf_token %}
    <div class="form-row">
        <ul class="errorlist">
            {% if  mensaje == 0 %}
            <li>Error: Fecha de inicio debe ser menor a la fecha de finalizacion</li>
                {% elif mensaje == 1 %}
                <li>Error: La fecha debe ser mayor al dia de hoy</li>
                {% elif mensaje == 2 %}
                <li>Error: El usuario elegido no esta autorizado para ser Lider</li>
            {% endif %}
        </ul>
            {{ formulario.as_p }}
        </div>
    <div class="submit-row">
        <input type='submit' value='Cancelar' onClick='history.go(-1);'>
        <input type="submit" value="Confirmar" />
    </div>
</form>
            </fieldset>
                    </div>

{% endblock %}