GestionP/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django import setup
setup()
admin.autodiscover()

urlpatterns =  [
    url(r'^$', include('RegistroApp.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^usuarios/', include('usuarios.urls')),
    #url(r'^cliente/', include('cliente.urls')),
    url(r'^roles/',include('roles.urls')),
    url(r'^proyectos/',include('proyectos.urls')),
    url(r'^equipos/', include('equipos.urls')),
    url(r'^flujos/', include('flujos.urls')),
    url(r'^actividades/', include('actividades.urls')),
    url(r'^userStories/', include('userStories.urls')),
    url(r'^sprints/', include('sprints.urls')),
    url(r'^trabajos/', include('trabajos.urls')),
]

roles/urls.py
from django.conf.urls import url
from django.contrib import admin
admin.autodiscover()

from .views import crear_rol, detalle_rol, lista_roles, editar_rol, RegisterSuccessView, eliminar_rol

urlpatterns =  [
    url(r'^crear/$', crear_rol, name='crear_rol'),
    url(r'^$',lista_roles,name='lista_roles'),
    url(r'^(?P<id_rol>\d+)$', detalle_rol, name='detalle_rol'),
    url(r'^eliminar/(?P<id_rol>\d+)$', eliminar_rol, name='eliminar_rol'),
    url(r'^modificar/(?P<id_rol>\d+)$', editar_rol, name='editar_rol'),
    url(r'^register/success/$',RegisterSuccessView.as_view()),
]
print(urlpatterns)

userStories/urls.py
from django.conf.urls import patterns, url
from django.contrib import admin
from userStories.views import listar_userStories, crear_userStory, detalle_userStory, editar_userStory, eliminar_userStory
from trabajos.views import listar_trabajos

admin.autodiscover()


urlpatterns = [
                       url(r'^crear/(?P<id_proyecto>\d+)$',crear_userStory, name='crear_userStories'),
                       url(r'^(?P<id_proyecto>\d+)$',listar_userStories, name='listar_userStories'),
                       url(r'^detalle/(?P<id_userStory>\d+)$',detalle_userStory, name='detalle_userStory'),
                       url(r'^modificar/(?P<id_userStory>\d+)$',editar_userStory, name='editar_userStory'),
                       url(r'^eliminar/(?P<id_userStory>\d+)$',eliminar_userStory,name='eliminar_userStory'),
                       url(r'^trabajos/(?P<id_userStory>\d+)$', listar_trabajos, name='listar_trabajos'),
                       #url(r'^register/success/$', RegisterSuccessView, name='RegisterSuccessView'),
]

userStories/models.py
from django.db import models
from django.contrib.auth.models import Group
from flujos.models import Flujo
from django.contrib.auth.models import User
from proyectos.models import Proyecto
from sprints.models import Sprint
from actividades.models import Actividad
#from apps.trabajos.models import Trabajo


# Create your models here.



class UserStory(models.Model):
    """
    Modelo que representa a un User Story
    nombre: Cadena de caracteres
    descripcion: Un campo de texto
    tiempo: Entero positivo que representa la cantidad de tiempo en dias
    estado: Enum de los tipos de estados por los que puede pasar una fase: Pendiente, En Construccion, Finalizado, Validado, Revision, Anulado
    version: Entero corto con valores positivos
    orden: Entero corto que representa el orden relative de items
    relacion: clave foranea a otro item
    tipo: Enum de los tipos de relaciones entre items: Padre-Padre-Antecesor-Padre
    fecha_creacion: Tipo de dato Date
    proyecto: Clave foranea a un Proyecto
    desarrollador: Clave foranea a un Desarrollador
    fecha_mod: Clave foranea a a un Sprint
    actividad: Clave foranea a una Actividad
    """
    estados_kanban = ((0, 'ToDo'), (1, 'Doing'), (2, 'Done'), (3, 'Pendiente Aprobacion'), (4, 'Aprobado'))
    estados_scrum = ((0, 'Nuevo'), (1, 'Iniciado'), (2, 'Suspendido'), (3, 'Eliminado'))

    nombre = models.CharField(max_length=20, verbose_name='Nombre')
    descripcion = models.TextField(verbose_name='Descripcion')
    prioridad = models.IntegerField(choices=((i, i) for i in range(1, 10)), default=1)
    valor_negocio = models.PositiveIntegerField(verbose_name='Valor de Negocio')
    valor_tecnico = models.PositiveIntegerField(verbose_name='Valor Tecnico')
    tiempo_estimado = models.PositiveIntegerField(verbose_name='Tiempo Estimado en Horas')
    tiempo_registrado = models.PositiveIntegerField(verbose_name='Tiempo Registrado', default=0)
    ultimo_cambio = models.DateTimeField(auto_now=True, verbose_name='Ultimo Cambio')
    estadoKanban = models.IntegerField(choices=estados_kanban, default=0)
    estadoScrum = models.IntegerField(choices=estados_scrum, default=0)
    proyecto = models.ForeignKey(Proyecto)
    desarrollador = models.ForeignKey(User, null=True)
    sprint = models.ForeignKey(Sprint, null= True)
    flujo = models.ForeignKey(Flujo, null=True, blank=True)
    actividad = models.ForeignKey(Actividad, null=True, blank=True)
    version = models.PositiveIntegerField(null=True, blank=True)
    orden = models.PositiveIntegerField(null=True, blank=True)
    fecha_mod = models.DateField(verbose_name='Fecha de Modificacion', null=True)
    prioridad_obtenida = models.PositiveIntegerField(null=True, blank=True)
    #trabajo = models.ForeignKey(Trabajo, null=True, blank=True)


    def __str__(self):
        return self.nombre




class VersionUserStory(models.Model):
    """
    Modelo que representa a la version de un  User Story
    nombre: Cadena de caracteres
    descripcion: Un campo de texto
    tiempo: Entero positivo que representa la cantidad de tiempo en dias
    estado: Enum de los tipos de estados por los que puede pasar una fase: Pendiente, En Construccion, Finalizado, Validado, Revision, Anulado
    version: Entero corto con valores positivos
    orden: Entero corto que representa el orden relative de items
    relacion: clave foranea a otro item
    tipo: Enum de los tipos de relaciones entre items: Padre-Padre-Antecesor-Padre
    fecha_creacion: Tipo de dato Date
    proyecto: Clave foranea a un Proyecto
    desarrollador: Clave foranea a un Desarrollador
    fecha_mod: Clave foranea a a un Sprint
    actividad: Clave foranea a una Actividad
    """
    estados_kanban = ((0, 'ToDo'), (1, 'Doing'), (2, 'Done'), (3, 'Pendiente Aprobacion'), (4, 'Aprobado'))
    estados_scrum = ((0, 'Nuevo'), (1, 'Iniciado'), (2, 'Suspendido'), (3, 'Eliminado'))

    id_UserStory = models.ForeignKey(UserStory,  verbose_name='UserStory', related_name='userStoryVersion')
    nombre = models.CharField(max_length=20, verbose_name='Nombre')
    descripcion = models.TextField(verbose_name='Descripcion')
    prioridad = models.IntegerField(choices=((i, i) for i in range(1, 10)), default=1)
    valor_negocio = models.PositiveIntegerField(verbose_name='Valor de Negocio')
    valor_tecnico = models.PositiveIntegerField(verbose_name='Valor Tecnico')
    tiempo_estimado = models.PositiveIntegerField(verbose_name='Tiempo Estimado')
    ultimo_cambio = models.DateTimeField(auto_now=True, verbose_name='Ultimo Cambio')
    estadoKanban = models.IntegerField(choices=estados_kanban, default=0)
    estadoScrum = models.IntegerField(choices=estados_scrum, default=0)
    proyecto = models.ForeignKey(Proyecto)
    desarrollador = models.ForeignKey(User, null=True)
    flujo = models.ForeignKey(Flujo, null=True, blank=True)
    actividad = models.ForeignKey(Actividad, null=True, blank=True)
    version = models.PositiveIntegerField(null=True, blank=True)
    orden = models.PositiveIntegerField(null=True, blank=True)
    fecha_mod = models.DateField(verbose_name='Fecha de Modificacion')
    #trabajo = models.ForeignKey(Trabajo, null=True, blank=True)

    def __str__(self):
        return self.nombre

userStories/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.models import Group, User, Permission
from django.db.models import Q
from django.forms.models import modelformset_factory
from django.http import HttpResponse, StreamingHttpResponse, HttpResponseRedirect
from django.shortcuts import render, render_to_response, get_object_or_404, redirect
from datetime import datetime
from proyectos.models import Proyecto
# Create your views here.
from django.template import RequestContext
from django.core.urlresolvers import reverse_lazy
from GestionP import settings
from flujos.models import Flujo
from userStories.models import UserStory
from proyectos.models import Proyecto
from userStories.forms import crearUserStoryForm
from django import forms
from django.core.mail import EmailMessage, send_mail
from equipos.models import MiembroEquipo
from django.contrib.auth.models import User, Group



@login_required
def listar_userStories(request, id_proyecto):
    """
    vista para listar los userStories pertenecientes a la flujo
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    id_userStory: clave foranea a la flujo
    return render_to_response(..) o HttpResponse(...)
    """

    rolSM = Group.objects.filter(name="Scrum Master")
    permission_required(perm=rolSM)
    equipi = MiembroEquipo.objects.filter(rol = rolSM, proyecto_id = id_proyecto)
    if equipi.count() == 0:
        mensaje = 101
        proyectos = Proyecto.objects.all()
        #proyecto = Proyecto.objects.get(id=id_proyecto)
        rolSM = Group.objects.filter(name = "Scrum Master")
        equipos = MiembroEquipo.objects.filter(rol = rolSM)
        return render_to_response('proyectos/listar_proyectos.html', {'proyectos': proyectos, 'equipos' : equipos, 'mensaje': mensaje}, context_instance=RequestContext(request))
    else:
        #tuserStory=get_object_or_404(Flujo,id=id_flujo)
        #flujo=Flujo.objects.filter(id=id_flujo)
        #if es_miembro(request.user.id,flujo,''):
        userStories=UserStory.objects.filter(proyecto_id = id_proyecto)
        #if puede_add_userStories(flujo):
        nivel = 3
        #id_proyecto=Flujo.objects.get().proyecto_id
        #proyecto=Proyecto.objects.get(pk=UserStory.proyecto)
        return render_to_response('userStories/listar_userStories.html', {'datos': userStories, 'id_proyecto': id_proyecto, 'nivel':nivel},
                                  context_instance=RequestContext(request))
        #else:
        #ESTE HAY QUE CORREGIR SI HAY TIEMPO
        #return HttpResponse("<h1>No se pueden administrar los UserStories de esta flujo. La flujo anterior aun no tiene userStories finalizados<h1>")

        #else:
        #return render_to_response('403.html')




@login_required
def crear_userStory(request, id_proyecto):
    """
    Vista para crear un user story.
    request: objeto HttpRequest que representa la metadata de la solicitud HTTP
    id_proyecto: clave foranea al tipoItem
    render_to_response('/...) o render_to_response('403.html')
    """

    atri=1

    # print(cantidad_items(id_tipoItem))
    #id_fase=TipoItem.objects.get(id=id_tipoItem).fase_id
    #flag=es_miembro(request.user.id,id_fase,'add_item')


    #flujo=Flujo.objects.get(id=id_fase)
    #proyecto=flujo.proyecto_id
    #items=[]
    #tipoitem=[]
    #proyecto=Proyecto.objects.get(UserStory.proyecto)
    rolSM = Group.objects.filter(name="Scrum Master")
    permission_required(perm=rolSM)

    if request.method=='POST':
        #formset = ItemFormSet(request.POST)
        formulario = crearUserStoryForm(request.POST)

        if formulario.is_valid():
            today = datetime.now() #fecha actual
            dateFormat = today.strftime("%Y-%m-%d") # fecha con format
            #obtener item con el cual relacionar
            #item_nombre=request.POST.get('entradalista')

            newUserStory=UserStory(nombre=request.POST['nombre'],descripcion=request.POST['descripcion'],prioridad=request.POST['prioridad'],
                                   valor_negocio=request.POST['valor_negocio'],valor_tecnico=request.POST['valor_tecnico'],tiempo_estimado=request.POST['tiempo_estimado'],
                                   ultimo_cambio=datetime, proyecto_id=id_proyecto, flujo_id = None, estadoScrum=0)

            newUserStory.prioridad_obtenida = int(int(newUserStory.prioridad)/3 + int(newUserStory.valor_tecnico)/3 + int(newUserStory.valor_negocio)/3)

            newUserStory.save()
            # enviar correo de notificacion al scrum master
            # proyecto = newUserStory.proyecto
            # id_proyecto = proyecto.id
            #newUserStory.prioridad_obtenida = newUserStory.prioridad + newUserStory.valor_tecnico + newUserStory.valor_negocio
            objdev = request.user
            proyecto = newUserStory.proyecto
            desarrollador = User.get_full_name(objdev)
            #rolSM = Group.objects.filter(name = "Scrum Master")
            equipi = MiembroEquipo.objects.get(rol = rolSM, proyecto_id = id_proyecto)
            SM = equipi.usuario
            correo = SM.email
            historico = "User Story " + str(newUserStory.nombre) + " creado por:  " + str(equipi.usuario) + " en fecha " + str(today)
            # print str(userStory_nuevo.flujo.nombre)
            # print (correo)
            # send_mail("Asunto", "Mensaje del sistema. \nEl usuario " + str(
            #    desarrollador) + " ha editado el siguiente User Story\n" +
            #          "\nNombre: " + userStory_nuevo.nombre +
            #          "\nDescrpcion: " + userStory_nuevo.descripcion +
            #          "\nPrioridad: " + str(userStory_nuevo.prioridad) +
            #          "\nValor de negocio: " + str(userStory_nuevo.valor_negocio) +
            #          "\nValor tecnico: " + str(userStory_nuevo.valor_tecnico) +
            #         "\nTiempo estimado: " + str(userStory_nuevo.tiempo_estimado) +
            #         "\nUltimo cambio: " + str(userStory_nuevo.ultimo_cambio) +
            #          "\nEstado del Kanban: " + str(userStory_nuevo.estadoKanban) +
            #          "\nEstado del Scrum: " + str(userStory_nuevo.estadoScrum),
            #          '"GestionP" <gestionp.is2@gmail.com>', [correo])
            send_mail("Asunto", historico,
                      '"GestionP-Administrador del Sistema"',
                      [correo])

        return render_to_response('userStories/creacion_correcta.html',{'id_proyecto': id_proyecto}, context_instance=RequestContext(request))
    else:
        formulario = crearUserStoryForm()
        hijo=False
        #proyecto=Proyecto.objects.filter(id=flujo.proyecto_id)
        return render_to_response('userStories/crear_userStories.html', { 'formulario': formulario, 'id_proyecto': id_proyecto}, context_instance=RequestContext(request))




@login_required
def editar_userStory(request,id_userStory):
    '''
    vista para cambiar el nombre y la descripcion del tipo de user story, y ademas agregar atributos al mismo
    Si el user story se encuentra con el estado CON (solicitud de cambio aprobada), se puede modificar el user story solo si el
    usuario es el que realizo la solicittud de cambio
    '''

    rolSM = Group.objects.filter(name="Scrum Master")
    permission_required(perm=rolSM)
    userStory_nuevo=get_object_or_404(UserStory,id=id_userStory)
    if request.method=='POST':
        formulario = crearUserStoryForm(request.POST, instance=userStory_nuevo)
        if formulario.is_valid():
            #generar_version(item_nuevo)
            today = datetime.now() #fecha actual
            dateFormat = today.strftime("%Y-%m-%d") # fecha con format

            formulario.save()
            userStory_nuevo.fecha_mod=dateFormat
            #userStory_nuevo.version=userStory_nuevo.version+1
            userStory_nuevo.save()

            # enviar correo de notificacion al scrum master
            objdev = request.user
            desarrollador = User.get_full_name(objdev)
            proyecto = userStory_nuevo.proyecto
            id_proyecto = proyecto.id
            rolSM = Group.objects.filter(name = "Scrum Master")
            equipi = MiembroEquipo.objects.get(rol = rolSM, proyecto_id = id_proyecto)
            # equipi = MiembroEquipo.objects.get(proyecto_id = id_proyecto)
            SM = equipi.usuario
            correo = SM.email
            historico = "User Story " + str(userStory_nuevo.nombre) + " modificado por:  " + str(equipi.usuario) + " en fecha " + str(today)
            # print str(userStory_nuevo.flujo.nombre)
            # print (correo)
            #send_mail("Asunto", "Mensaje del sistema. \nEl usuario " + str(
            #    desarrollador) + " ha editado el siguiente User Story\n" +
            #          "\nNombre: " + userStory_nuevo.nombre +
            #          "\nDescrpcion: " + userStory_nuevo.descripcion +
            #          "\nPrioridad: " + str(userStory_nuevo.prioridad) +
            #          "\nValor de negocio: " + str(userStory_nuevo.valor_negocio) +
            #          "\nValor tecnico: " + str(userStory_nuevo.valor_tecnico) +
            #         "\nTiempo estimado: " + str(userStory_nuevo.tiempo_estimado) +
            #         "\nUltimo cambio: " + str(userStory_nuevo.ultimo_cambio) +
            #          "\nEstado del Kanban: " + str(userStory_nuevo.estadoKanban) +
            #          "\nEstado del Scrum: " + str(userStory_nuevo.estadoScrum),
            #          '"GestionP" <gestionp.is2@gmail.com>', [correo])
            send_mail("Asunto",historico,
                      '"GestionP-Administrador del Sistema"',
                      [correo])
            return render_to_response('userStories/creacion_correcta.html',{'id_proyecto': id_proyecto}, context_instance=RequestContext(request))

    else:
        formulario = crearUserStoryForm(instance=userStory_nuevo)

userStories/templates/userStories/creacion_correcta.html
{% extends 'base2.html' %}
{% block title %}
User Story Exitoso
{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="es-PY" >
<head>
    <meta http-equiv="Refresh" content="2; /userStories/{{id_proyecto}}">
    <link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />

    <script type="text/javascript">window.__admin_media_prefix__ = "/static/usuario/";</script>

    <meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class="">

<!-- Container -->
<div id="content">

    <!-- Content -->
    <div class="colM">


        <h1>Registro de User Story exitoso</h1>


        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>
{% endblock %}

userStories/templates/userStories/crear_userStories.html
{% extends 'base2.html' %}
{% block title %}
GestionP-Nuevo User Story
{% endblock %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/usuario/css/forms.css" />

</head>

<div id="content">
    <h1>Crear User Story</h1>
    <fieldset class="module aligned wide">
        <form method='post' action='' enctype="multipart/form-data">{% csrf_token %}
            <div class="form-row" >
                {{formulario.as_p}}
                <br>

            </div>
    <div class="submit-row">
        <input type='submit' value='Cancelar' onClick='history.go(-1);'>
        <input type="submit" value="Confirmar" />
    </div>
</form>
</fieldset>
</div>

{% endblock %}

userStories/templates/userStories/detalle_userStory.html
{% extends 'base2.html' %}
{% block title %}
Detalle User Story
{% endblock %}
{% block content %}
<head>
    <link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/usuario/css/forms.css" />

</head>




<div id="content">
    <h1>Detalles de {{datos.nombre|title}}</h1>
    <fieldset class="module aligned wide">
        <form method="post">{% csrf_token %}
            <div class="form-row">
                <h3><div><strong>Nombre: </strong>{{ datos.nombre }}</div></th></h3>
                <h3><div><strong>Descripción: </strong>{{ datos.descripcion }}</div></h3>
                <h3><div><strong>Horas Estimadas: </strong>{{ datos.tiempo_estimado }}</div></h3>
                <h3><div><strong>Actividad: </strong>{{ datos.actividad }}</div></h3>
                <h3><div><strong>Estado: </strong>{{ datos.get_estadoKanban_display }}</div></h3>
                <h3><div><strong>Prioridad: </strong>{{ datos.prioridad }}</div></h3>
                <h3><div><strong>Proyecto: </strong>{{ datos.proyecto }}</div></h3>
                <h3><div><strong>Desarrollador: </strong>{{ datos.desarrollador }}</div></h3>
                {% if datos.sprint == none %}
                    <h3><div><strong>Sprint: </strong>No asignado</div></h3>
                {% else %}
                    <h3><div><strong>Sprint: </strong>{{ datos.sprint }}</div></h3>
                {% endif %}

                <h3><div><strong>Flujo: </strong>{{ datos.flujo }}</div></h3>
                <h3><div><strong>Fecha de modificacion: </strong>{{ datos.fecha_mod }}</div></h3>
                <div class="submit-row">
                    <input type='submit' value='Retornar' onClick='history.go(-1);'>
                </div>
            </div>
        </form>
    </fieldset>

{% endblock %}

userStories/templates/userStories/editar_userStory.html
{% extends 'base2.html' %}
{% block title %}
	Modificar user story
{% endblock %}
{% block content %}
<head>
<link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/usuario/css/forms.css" />
</head>


<div id="content">
    <div class="change-list" style="width: 1000px">
        <h1>Modificar User Story {{item.nombre|title}}</h1>
        <fieldset class="module aligned wide">
        <form method="post">{% csrf_token %}
            <div class="form-row">
                {{ formulario.as_p }}
            </div>
            <div class="submit-row">
                <input type='submit' value='Cancelar' onClick='history.go(-1);'>
                <input type="submit" value="Guardar Cambios" />
            </div>
        </form>
        </fieldset>
    </div>
</div>
{% endblock %}

userStories/templates/userStories/listar_userStories.html
{% extends 'base2.html' %}
{% block title %}
GestionP-User Stories
{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="es-PY" >
<head>
<link rel="stylesheet" type="text/css" href="/static/usuario/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/usuario/css/changelists.css" />

<script type="text/javascript">window.__admin_media_prefix__ = "/static/usuario/";</script>
<script type="text/javascript" src="/static/usuario/js/core.js"></script>
<script type="text/javascript" src="/static/usuario/js/jquery.js"></script>
<script type="text/javascript" src="/static/usuario/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/usuario/js/actions.js"></script>
<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class="dashboard">

<!-- Container -->
<div id="content" class="change-list" style="width: 1100px">
    <!-- Content -->
        <h1>Product Backlog</h1>

<ul class="btn1">
    <li>
        <a href="/userStories/crear/{{ id_proyecto}}" class="addlink">Nuevo User Story</a>
    </li>
</ul>
<div id="content-main">

        <div class="results" >
         <!--ul class="errorlist">
            {% if  mensaje == 0 %}
            <li>Error: No se puede eliminar un item que tenga hijos</li>
                {% elif mensaje == 2 %}
                <li>Error:  No se puede eliminar un item cuyo estado no sea pendiente.</li>
            {% endif %}
        </ul-->
        <ul class="infolist">
            {% if mensaje == 1 %}
            <li>Item eliminado correctamente</li>
            {% endif %}
        </ul>
        <table >
        <thead>
        <tr>
            <th scope="col" class="sortable" >
                <div class="text">
                    Nombre
                </div>
            </th>
            <th scope="col">
                <div class="text">
                    Prioridad
                </div>
            </th>
             <th scope="col">
                <div class="text">
                    Estado
                </div>
            </th>
             <th scope="col">
                <div class="text">
                    TiempoEstimado
                </div>
            </th>
            <th scope="col">
                <div class="text">
                    TiempoRegistrado
                </div>
            </th>
            <th scope="col">
                <div class="text">
                    UltimoCambio
                </div>
            </th>
                </div>
            </th>
            <th scope="col">
                <div class="text">
                    Descripcion
                </div>
            </th>
             <th scope="col">
                <div class="text">
                    Modificar
                </div>
             </th>
            <th scope="col">
                <div class="text">
                    Eliminar
                </div>
            </th>
            <!--th scope="col">
                <div class="text">
                    Trabajos
                </div>
            </th-->
        </tr>
        </thead>
        <tbody>
        {% for dato in datos  %}
            <tr>
                <td><center>{{ dato.nombre}}</center></td>
                <td><center>{{ dato.prioridad_obtenida}}</center></td>
				<td><center>{{ dato.get_estadoScrum_display }}</center></td>
                <td><center>{{ dato.tiempo_estimado }}</center></td>
                <td><center>{{ dato.tiempo_registrado }}</center></td>
                <td><center>{{ dato.ultimo_cambio }}</center></td>
                <td><center><a href="/userStories/detalle/{{ dato.id }}"  class="btn btn-success"><i class="icon-eye-open icon-white"></i></a></center></td>
                <td><center><a href="/userStories/modificar/{{ dato.pk }}" class="btn btn-primary"><i class="icon-pencil icon-white"></i></a></center></td>
                <td><center><a href="/userStories/eliminar/{{ dato.pk }}" class="btn btn-danger"><i class=" icon-trash icon-white"></i></a></center></td>

                <!--td><center><a href="/trabajos/userStories/{{ dato.pk }}" class="btn btn-info"><i class="icon-bookmark icon-white"></i></a></center></td-->
            </tr>
        {% endfor %}
        </tbody>

        </table>
        </div>


</div>



        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>
{% endblock %}